import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

import Navbar from '../components/Navbar'

import { useEffect,useState } from 'react'

import {IntlProvider,FormattedMessage} from 'react-intl'
import english from '../lang/en.json'
import spansih from '../lang/es.json'
import About from '../components/About'

export default function Home() {

  const [language, setLanguage] = useState(english)

  
  useEffect(() => {
    const options={
      root:null,
      threshold:0.5,
      rootMargin:"0px"
    }
    const observer= new IntersectionObserver((entries)=>{
      entries.forEach(entry=>{
         if(entry.isIntersecting){
            entry.target.classList.remove(styles.disappear)
            entry.target.classList.add(styles.appear)
         }
         else{
            entry.target.classList.remove(styles.appear)
            entry.target.classList.add(styles.disappear)
         }
      })
    },options)
    const sections=document.querySelectorAll("section")
    sections.forEach(section=>observer.observe(section))
  })

  function changeLanguage(lang){
    switch (lang) {
      case "en":
        setLanguage(english)
        break;
      case "es":
        setLanguage(spansih)
        break;
      default:
        setLanguage(english)
        break;
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Daniel Estrada</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      
      <IntlProvider locale="en" messages={language}>
        <Navbar changeLanguage={changeLanguage}/>
        <main className={styles.main}>

          <section id="home" className={styles.home}>
            <span><FormattedMessage id="hi"/></span>
            <h1>DANIEL<br/>ESTRADA</h1>
            <span><FormattedMessage id="i-am"/></span>
          </section>

          <section id="about" className={`${styles.section} ${styles.about}`}>
            <h2 className={styles.title}><FormattedMessage id="about"/></h2>
            <div className={styles.about_container}>
              <div>
                  <p><FormattedMessage id="about-text"/></p>
                  <p>He aqui algunas teconologias con las que me siento comodo trabajando :</p>
                  <ul className={styles.tecnologies_list}>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://developer.mozilla.org/es/docs/Web/JavaScript">JavaScript</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://developer.mozilla.org/es/docs/Web/HTML">HTML</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://developer.mozilla.org/es/docs/Web/CSS">CSS</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://sass-lang.com/">SASS</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://getbootstrap.com/">Bootstrap</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://reactjs.org/">React</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://nextjs.org/">Next</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://nodejs.org/en/">Node</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://www.java.com/en/">Java</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://www.python.org/">Python</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://www.typescriptlang.org/">TypeScript</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://git-scm.com/">Git</a></li>
                  </ul>
              </div>
              <div className={styles.profile_container}>
              </div>
            </div>
          </section>

          <section id="projects" className={`${styles.section} ${styles.projects}`}>
            <h2 className={styles.title}><FormattedMessage id="projects"/></h2>
          </section>

         
          <section id="contact" className={`${styles.section} ${styles.contact}`}>
            <h2 className={styles.title}><FormattedMessage id="contact"/></h2>
            <p className={styles.subtitle}>Have some time? you can ask me questions here if i am avaliable</p>
          </section>

        </main>
      </IntlProvider>
    </div>
  )
}
