import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.scss'

import Navbar from '../components/Navbar'
import Chat from '../components/Chat'

import { useEffect,useState } from 'react'

import {IntlProvider,FormattedMessage} from 'react-intl'
import english from '../lang/en.json'
import spansih from '../lang/es.json'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faEnvelope,faMobileAlt,faExternalLinkAlt } from '@fortawesome/free-solid-svg-icons'
import {faGithub,faLinkedin,faSkype} from '@fortawesome/free-brands-svg-icons'



export default function Home() {

  const [language, setLanguage] = useState(english)

  const [conect, setConect] = useState("Daniel is connected")
  const [desconect, setDesconect] = useState("Daniel is not connected")

  
  useEffect(() => {
    const options={
      root:null,
      threshold:0.4,
      rootMargin:"0px"
    }
    const observer= new IntersectionObserver((entries)=>{
      entries.forEach(entry=>{
         if(entry.isIntersecting){
            entry.target.classList.remove(styles.disappear)
            entry.target.classList.add(styles.appear)
         }
         else{
            entry.target.classList.remove(styles.appear)
            entry.target.classList.add(styles.disappear)
         }
      })
    },options)
    const sections=document.querySelectorAll("section")
    sections.forEach(section=>observer.observe(section))
  })

  function changeLanguage(lang){
    switch (lang) {
      case "en":
        setDesconect("Daniel is not connected")
        setConect("Daniel is connected")
        setLanguage(english)
        break;
      case "es":
        setDesconect("Daniel no esta conectado")
        setConect("Daniel esta conectado")
        setLanguage(spansih)
        break;
      default:
        setLanguage(english)
        break;
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Daniel Estrada</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      
      <IntlProvider locale="en" messages={language}>
        <Navbar changeLanguage={changeLanguage}/>
        <main className={styles.main}>

          <section id="home" className={styles.home}>
            <span><FormattedMessage id="hi"/></span>
            <h1>DANIEL<br/>ESTRADA</h1>
            <span><FormattedMessage id="i-am"/></span>
          </section>

          <section id="about" className={`${styles.section} ${styles.about}`}>
            <h2 className={styles.title}><FormattedMessage id="about"/></h2>
            <div className={styles.about_container}>
              <div>
                  <p><FormattedMessage id="about-text"/></p>
                  <p><FormattedMessage id="skills-text"/></p>
                  <ul className={styles.tecnologies_list}>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://developer.mozilla.org/es/docs/Web/JavaScript">JavaScript</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://developer.mozilla.org/es/docs/Web/HTML">HTML</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://developer.mozilla.org/es/docs/Web/CSS">CSS</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://sass-lang.com/">SASS</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://getbootstrap.com/">Bootstrap</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://reactjs.org/">React</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://nextjs.org/">Next</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://nodejs.org/en/">Node</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://www.java.com/en/">Java</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://www.python.org/">Python</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://www.typescriptlang.org/">TypeScript</a></li>
                    <li className={styles.tecnologie_item}><a target="_blank" rel="noreferrer" href="https://git-scm.com/">Git</a></li>
                  </ul>
              </div>
              <div className={styles.profile_container}>
                <Image src="/profile.jpg" layout="responsive" width="4" height="5" className={styles.profile} />
              </div>
            </div>
          </section>

          <section id="projects" className={`${styles.section} ${styles.projects}`}>
            <h2 className={styles.title}><FormattedMessage id="projects"/></h2>
            <div className={styles.card_container}>
              <div className={styles.card}>
                <Image src="/ezapi.png" layout="responsive" width="5" height="3" className={styles.card_image}/>
                <div className={styles.card_text}>
                  <h3>EZ API</h3>
                  <p><FormattedMessage id="ezapi-description"/></p>
                </div>
                <div className={styles.card_links}>
                  <a href="https://ezapi.vercel.app/" target="_blank" rel="noreferrer"><FormattedMessage id="visit"/><FontAwesomeIcon icon={faExternalLinkAlt}/></a>
                </div>
              </div>
            </div>
          </section>

         
          <section id="contact" className={`${styles.section} ${styles.contact}`}>
            <h2 className={styles.title}><FormattedMessage id="contact"/></h2>
            <p className={styles.subtitle}><FormattedMessage id="contact-subtitle"/></p>
            <Chat conectMessage={conect} desconectMessage={desconect}/>
          </section>

        </main>

        <footer className={styles.footer}>
          <ul className={styles.contact_list}>
            <li className={styles.list_item}><a href="https://github.com/danielsitio" target="_blank" rel="noreferrer"><FontAwesomeIcon icon={faGithub}/></a></li>
            <li className={styles.list_item}><a href="https://www.linkedin.com/in/daniel-fernando-estrada-escaray-004981222/" target="_blank" rel="noreferrer"><FontAwesomeIcon icon={faLinkedin}/></a></li>
            <li className={styles.list_item}><a href="mailto:danest.esc@gmail.com"><FontAwesomeIcon icon={faEnvelope}/></a></li>
          </ul>
          <div>
            
          </div>
        </footer>
      </IntlProvider>
    </div>
  )
}
